### ISSUE TITLE
missing requirement: jmespath

### ISSUE THREAD

**Issue by bmbufalo** [automateyournetwork/WindowsFacts#1]
First off: this is wonderful and exactly what I needed! Thanks for making this!

I encountered this issue: 

``` 
 FAILED! => {"msg": "You need to install \"jmespath\" prior to running json_query filter"}
```

And the [solution](https://github.com/ansible-ThoTeam/nexus3-oss/issues/205) was to add the requirement: 

```
pip install jmespath
```

Hope this helps!

**Comment by automateyournetwork** [comment]
Thank you I will add it to the read me!!! Glad you like it / find it useful!

**Comment by automateyournetwork** [comment]
Added to read me as a high level requirement
